version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - run: echo "hello world!"
      
# cheekit-test has left from this org
# cheekit-test has left from this org 1 mins left
# cheekit-test has left from this org 4 days left
